type Props = {}
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: " About page ",
  description: "Generated by create next app",
};
import AboutPage from "./about"
export default function About({ }: Props) {
  return (
    <div>
      <AboutPage />
    </div>
  )
}
