import ContactPage from './contact'
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: " Contact page ",
  description: "Generated by create next app",
};
type Props = {}

export default function Contact({}: Props) {
  return (
    <div> 
      <ContactPage />
    </div>
  )
}
