import { Metadata } from 'next';
export const metadata: Metadata = {
  title: " Home page ",
  description: "Generated by create next app",
};
const Home = () => {
  return (
    <div className='text-center '>
      <h1 className='py-5 mt-5 text-4xl font-bold text-red-500 underline bg-amber-500'>Home</h1>
      <p className='pt-5 text-sm text-blue-900'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia quasi, minima rem, mollitia magnam quae eligendi distinctio blanditiis labore voluptates, ab reprehenderit doloribus tempora deleniti corporis nostrum nulla aspernatur aliquam!</p>
    </div>
  )
};


export default Home
